### ISSUE TITLE
Fatal TypeError

### ISSUE THREAD

**Issue by szachara** [sensiolabs/security-checker#96]
I'm using SecurityChecker few months without problem, today I get this error.

I didn't change anything in composer.lock or composer.json.

```
Fatal error: Uncaught TypeError: Argument 3 passed to SensioLabs\Security\Formatters\TextFormatter::displayResults() must be of the type array, null given, called in E:\htdocs\fm-logistic\vendor\sensiolabs\security-checker\SensioLabs\Security\Command\SecurityCheckerCommand.php on line 102 and defined in E:\htdocs\fm-logistic\vendor\sensiolabs\security-checker\SensioLabs\Security\Formatters\TextFormatter.php:33
Stack trace:
#0 E:\htdocs\fm-logistic\vendor\sensiolabs\security-checker\SensioLabs\Security\Command\SecurityCheckerCommand.php(102): SensioLabs\Security\Formatters\TextFormatter->displayResults(Object(Symfony\Component\Console\Output\ConsoleOutput), './composer.lock', NULL)
#1 E:\htdocs\fm-logistic\vendor\symfony\console\Command\Command.php(264): SensioLabs\Security\Command\SecurityCheckerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 E:\htdocs\fm-logistic\vendor\symfony\console\Application.php(869): Symfony\Component\Console\Command\Co in E:\htdocs\fm-logistic\vendor\sensiolabs\security-checker\SensioLabs\Security\Formatters\TextFormatter.php on line 33
```

**Comment by laurencei** [comment]
I have same issue. Looks like JSON is no longer being returned from the API despite being requested.

**Comment by stefandoorn** [comment]
Same issue in here. Seems indeed response is different than before.

**Comment by smithandre** [comment]
Same issue. Any ideas as to what has changed?

**Comment by frenck** [comment]
Same issue here...

**Comment by mjrider** [comment]
Same here

**Comment by laurencei** [comment]
ping @simensen

**Comment by brammittendorff-dd** [comment]
Same issue here. When I check it online:
https://security.sensiolabs.org/check

It says 404 not found:
```Request URL:https://security.sensiolabs.org/check_lock.html
Request Method:POST
Status Code:404 Not Found
Remote Address:46.137.84.166:443
Referrer Policy:no-referrer-when-downgrade```

**Comment by simensen** [comment]
It looks like the service is experiencing some issues right now. Thanks for helping raise the issue.

**Comment by tucksaun** [comment]
@szachara Thanks for reporting this issue.
Should be fixed now.

**Comment by fabpot** [comment]
#97 is an attempt to display a better error message in such cases. Note that it would not make it work magically, but at least, you would not get an ugly PHP error message.
